# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60ead4b628c61842c3ad79e70d6eadd2c9e1fdb3bcdf9a129ede3cc7ad9897c4a9da61296925dd753fdc3c170d8f73711fd3a425c9b7b65f39a75de150e422d4

test:
  secret_key_base: 64951356128b39814cc9d3273417ad9388e18c65c98751e29840a9403183bff63b6bc9a5899a422b8380a377c0a0ebd397b19fe9dba93799f4d70b82c6fe269d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
